# @format

name: Deploy NextJS to VPS

on:
    push:
        branches:
            - main # Запуск при пуше в main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Deploy to VPS via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      echo "🚀 Начало деплоя NextJS"

                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                      nvm use 22
                      echo "✅ Node.js настроен"

                      cd /var/www/client.top24.kz
                      echo "✅ Перешли в папку проекта"

                      echo "⚡ Обновляем код из репозитория..."
                      git fetch --all
                      git reset --hard origin/main
                      git pull origin main || { echo "❌ Ошибка обновления репозитория!"; exit 1; }
                      echo "✅ Репозиторий обновлён"

                      echo "⚡ Удаляем .next, npded_modules, ..."
                      rm -rf .next node_modules package-lock.json
                      echo "✅ .next node_modules package-lock.json удалены"

                      echo "⚡ Устанавливаем зависимости..."
                      npm install --verbose || { echo "❌ Ошибка установки зависимостей!"; exit 1; }
                      echo "✅ Зависимости установлены"

                      echo "⚡ Билдим проект..."
                      npm run build || { echo "❌ Ошибка сборки проекта!"; exit 1; }
                      echo "✅ Сборка завершена"

                      echo "⚡ Перезапускаем сервер через PM2..."
                      pm2 restart client || { echo "❌ Ошибка перезапуска PM2!"; exit 1; }
                      echo "✅ Деплой NextJS завершён успешно!"
