# @format

name: Deploy NextJS to VPS

on:
    push:
        branches:
            - main # Запуск при пуше в main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Deploy to VPS via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /var/www/client.top24.kz
                      git pull origin main
                      npm install
                      npm build
                      pm2 restart client
